export const FETCHING_APPS_PENDING = "FETCHING_APPS_PENDING";
export const FETCHING_APPS_SUCCESS = "FETCHING_APPS_SUCCESS";
export const SCRAP_APPS = "SCRAP_APPS";
export const CHECK_SCRAPPING_STATUS = "CHECK_SCRAPPING_STATUS";
export const FETCHING_APPS_FAILURE = "FETCHING_APPS_FAILURE";

export const FETCHING_APP_DETAIL_SUCCESS = "FETCHING_APP_DETAIL_SUCCESS";
export const FETCHING_APP_DETAIL_PENDING = "FETCHING_APP_DETAIL_PENDING";
export const FETCHING_APP_DETAIL_FAILURE = "FETCHING_APP_DETAIL_FAILURE";

